# These are supported funding model platforms

This is a little awkward, but everything costs money...
Long story short, I've chosen patreon as a venue for supporting this work on an ongoing basis. 

As a privacy advocate and developer, I think the best I can do in this world is to build a replacement for the dark pattern riddled websites we use every day today. While we're building a new social platform, why not incorporate some 3D graphics, make the whole thing ad free, free to use, and open source? I think we can have nice things. 

patreon: leudla
